INSERT INTO `category` VALUES  
('Collecting', 'The hobby of collecting includes seeking, locating, acquiring, organizing, cataloging, displaying, storing, and maintaining whatever items are of interest to the individual collector. Some collectors are generalists, accumulating merchandise, or stamps from all countries of the world. Others focus on a subtopic within their area of interest, perhaps 19th century postage stamps, milk bottle labels from Sussex, or Mongolian harnesses and tack.', 'categories.jpg'), 
('Outdoor recreation', 'Outdoor pursuits are the group of activities which are dependent on the outdoors, These hobbies include gardening, hill walking, hiking, backpacking, canoeing, climbing, caving, fishing, wildlife viewing and engaging in watersports and snowsports. Depending on an individuals desired level of adrenaline, outdoors experiences are considered one type of hobby. While many enjoy an adrenaline rush or just an escape from reality, outdoor recreational activities can also be an extremely effective medium in education and team building. It is this ethos that has given rise to links with young people, such as the Duke of Edinburgh Award and PGL, and large numbers of outdoor education centers that have been established as the stress on the importance of a balanced and widespread education continues to grow.', 'categories.jpg'), 
('Performing arts', 'Many hobbies involve performances by the hobbyist, such as singing, acting, juggling, magic, dancing, playing a musical instrument, martial arts and other performing arts.', 'categories.jpg'), 
('Creative hobbies', 'Some hobbies result in an end product. Examples of this would be woodworking, photography, moviemaking, jewelry making, software projects such as Photoshopping and home music or video production, making bracelets, artistic projects such as drawing, painting, etc., creating models out of cardstock or paper - called papercraft. Hobbies also include higher-end projects like building or restoring a car, or building a computer from scratch. For computer savvy do-it-yourself hobbyists, CNC (Computer Numerical Control) machining is also popular. A CNC machine can be assembled and programmed to make different parts from wood or metal.', 'categories.jpg'), 
('Scale modelling', 'Making a replica of a real object in a smaller scale goes back to prehistoric times with small clay dolls and other children toys having been found near known populated areas. The Greeks, Romans, and Persians took the form to a greater depth during their years of world domination, using scale replicas of enemy fortifications, coastal defense lines, and other geographic fixtures to plan battles. At the turn of the Industrial Age and on through the 1920s, families could often afford things such as electric trains, wind-up toys (typically boats or cars) and the increasingly valuable tin toy soldiers.', 'categories.jpg'), 
('Cooking', 'Cooking requires applying heat to a food which usually, though not always, chemically transforms it, thus changing its flavor, texture, appearance, and nutritional properties. It encompasses a vast range of methods and tools, and may also be used to improve the digestibility of food. It may require the selection, measurement and combining of ingredients in an ordered procedure in an effort to achieve the desired result. Constraints on success include the ambient conditions, tools and the skill of the individual cook.', 'categories.jpg'), 
('Gardening', 'Residential gardening most often takes place in or about ones own residence, in a space referred to as the garden. Although a garden typically is located on the land near a residence, it may also be located on a roof, in an atrium, on a balcony, in a windowbox, or on a patio or vivarium. Gardening also takes place in non-residential green areas, such as parks, public or semi-public gardens (botanical gardens or zoological gardens), amusement and theme parks, along transportation corridors, and around tourist attractions and hotels. In these situations, a staff of gardeners or groundskeepers maintains the gardens.', 'categories.jpg'), 
('Reading', 'Reading, such as reading books, ebooks, magazines, comics, or newspapers, along with browsing the internet is a common hobby, and one that can trace its origins back hundreds of years. A love of literature, later in life, may be sparked by an interest in reading children literature as a child.', 'categories.jpg'), 
('Sports', 'People who enjoy playing sports may be amateur athletes who play recreationally.', 'categories.jpg'), 
('Other', 'All other interest groups', 'categories.jpg');