INSERT INTO `group_category` VALUES  
('Amateur radio', 'Creative hobbies'), 
('Audiophilia', 'Creative hobbies'), 
('Baking', 'Cooking'), 
('Basket Weaving', 'Creative hobbies'), 
('Bboying', 'Outdoor recreation'), 
('Baton twirling', 'Outdoor recreation'), 
('Chainmail making', 'Creative hobbies'), 
('Computer programming', 'Other'), 
('Conlanging', 'Other'), 
('Cooking', 'Cooking'), 
('Coloring', 'Creative hobbies'), 
('Crocheting', 'Creative hobbies'), 
('Creative writing', 'Creative hobbies'), 
('Dance', 'Performing arts'), 
('Drawing', 'Creative hobbies'), 
('Fantasy Football', 'Sports'), 
('Fishkeeping', 'Sports'), 
('Genealogy', 'Collecting'), 
('Herpetoculture', 'Gardening'), 
('Home automation', 'Other'), 
('Home Movies', 'Creative hobbies'), 
('Inline Skating', 'Sports'), 
('Jewelry making', 'Performing arts'), 
('Knapping', 'Creative hobbies'), 
('Knitting', 'Creative hobbies'), 
('Lapidary', 'Creative hobbies'), 
('Locksport', 'Other'), 
('Musical instruments', 'Performing arts'), 
('Painting', 'Creative hobbies');	